ALTER TYPE "PptPayoutReason" ADD VALUE IF NOT EXISTS 'PPT_LABEL_REMOVED';
ALTER TYPE "PptPayoutReason" ADD VALUE IF NOT EXISTS 'PPT_LABEL_REMOVED_DURING_PAYOUT_PROCESSING';
ALTER TYPE "PptPayoutReason" ADD VALUE IF NOT EXISTS 'PAID_ISSUE_LABEL_REMOVED';
ALTER TYPE "PptPayoutReason" ADD VALUE IF NOT EXISTS 'ISSUE_CANCELED';
ALTER TYPE "PptPayoutReason" ADD VALUE IF NOT EXISTS 'ISSUE_CANCELED_DURING_PAYOUT_PROCESSING';
ALTER TYPE "PptPayoutReason" ADD VALUE IF NOT EXISTS 'PAID_ISSUE_CANCELED';
ALTER TYPE "PptPayoutReason" ADD VALUE IF NOT EXISTS 'ISSUE_ARCHIVED_OR_TRASHED';
ALTER TYPE "PptPayoutReason" ADD VALUE IF NOT EXISTS 'ISSUE_ARCHIVED_DURING_PAYOUT_PROCESSING';
ALTER TYPE "PptPayoutReason" ADD VALUE IF NOT EXISTS 'PAID_ISSUE_ARCHIVED';
ALTER TYPE "PptPayoutReason" ADD VALUE IF NOT EXISTS 'PAID_ISSUE_NEEDS_REVIEW';
ALTER TYPE "PptPayoutReason" ADD VALUE IF NOT EXISTS 'ASSIGNEE_CHANGED_AFTER_PAYOUT_CHECK';
ALTER TYPE "PptPayoutReason" ADD VALUE IF NOT EXISTS 'ASSIGNEE_CHANGED_DURING_PAYOUT_PROCESSING';
ALTER TYPE "PptPayoutReason" ADD VALUE IF NOT EXISTS 'PAID_ISSUE_REASSIGNED';
ALTER TYPE "PptPayoutReason" ADD VALUE IF NOT EXISTS 'ESTIMATE_CHANGED_RECALCULATED';
ALTER TYPE "PptPayoutReason" ADD VALUE IF NOT EXISTS 'ESTIMATE_CHANGED_DURING_PROCESSING';
ALTER TYPE "PptPayoutReason" ADD VALUE IF NOT EXISTS 'PAID_ISSUE_ESTIMATE_CHANGED';
ALTER TYPE "PptPayoutReason" ADD VALUE IF NOT EXISTS 'STALE_LINEAR_WEBHOOK';

ALTER TYPE "PptPayoutEventType" ADD VALUE IF NOT EXISTS 'ISSUE_INVALIDATED';
ALTER TYPE "PptPayoutEventType" ADD VALUE IF NOT EXISTS 'ASSIGNEE_CHANGED';
ALTER TYPE "PptPayoutEventType" ADD VALUE IF NOT EXISTS 'ESTIMATE_CHANGED';
ALTER TYPE "PptPayoutEventType" ADD VALUE IF NOT EXISTS 'ESTIMATE_RECALCULATED';
ALTER TYPE "PptPayoutEventType" ADD VALUE IF NOT EXISTS 'PAID_ISSUE_MUTATED';
ALTER TYPE "PptPayoutEventType" ADD VALUE IF NOT EXISTS 'STALE_WEBHOOK_SKIPPED';

ALTER TABLE "PptPayoutState"
ADD COLUMN "latestLinearUpdatedAt" TIMESTAMP(3),
ADD COLUMN "canceledAt" TIMESTAMP(3),
ADD COLUMN "archivedAt" TIMESTAMP(3),
ADD COLUMN "trashed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "lastAssigneeChangeAt" TIMESTAMP(3),
ADD COLUMN "lastEstimateChangeAt" TIMESTAMP(3);

ALTER TABLE "PptPayoutState"
ALTER COLUMN "estimate" TYPE DOUBLE PRECISION USING "estimate"::DOUBLE PRECISION;

CREATE INDEX "PptPayoutState_latestLinearUpdatedAt_idx" ON "PptPayoutState"("latestLinearUpdatedAt");
