/**
 * DuitNow proxy identifiers ("DuitNow IDs").
 *
 * DuitNow lets someone be paid by a proxy — a mobile number, an NRIC, a
 * business registration number, a passport or an army/police number — instead
 * of a bank account number. Two facts about that shape this entire module:
 *
 *  1. **A proxy only works if it was explicitly registered.** Registration is
 *     per-ID, binds to exactly one account at one institution, and banks do
 *     not notify anyone when it fails. Nothing in the string reveals whether
 *     it happened; only the paying bank's lookup does. That is why the form
 *     asks for a confirmation and an admin records the lookup result, and why
 *     this module never pretends to verify.
 *
 *  2. **The type cannot be inferred from the value.** A Touch 'n Go eWallet
 *     account number is 12 digits, and so is an NRIC — and so are Maybank,
 *     Affin, China Construction Bank, Kuwait Finance House, Standard
 *     Chartered, Merchantrade, Boost, Setel and Instapay account numbers.
 *     There is no distinguishing prefix. Guessing misroutes money, so the type
 *     is always chosen by a person and stored beside the value.
 *
 * Client-safe and Prisma-free, so the form runs the exact same check while the
 * developer is typing that the server action runs on submit.
 *
 * ── Rules deliberately NOT implemented ──────────────────────────────────────
 * Each of these looks reasonable and would reject real MyKads:
 *
 *  - **No checksum.** The Malaysian NRIC has none. Singapore's does, which is
 *    where most "Malaysian IC validator" snippets inherit one from.
 *  - **No gender derivation.** The Deputy Home Minister confirmed in 2017 that
 *    the last digit does not indicate gender; the last four are generated by
 *    JPN's system. A real woman's MyKad ending in an odd digit cost her a visa.
 *  - **No place-of-birth allowlist.** Codes 60-93 are foreign birthplaces, 82
 *    is "state unknown", 98/99 stateless/refugee — all held by real citizens,
 *    some issued as recently as Dec 2024. JPN has never published the format
 *    and the public code tables contradict each other.
 *  - **No per-month day check and no leap-year check.** JPN's late-birth
 *    registration schemes for Sabah and Sarawak substitute nominal dates when
 *    a holder cannot document one, so an "impossible" date can be genuine.
 *    `isValidNricDate` stays at month 1-12 / day 1-31 on purpose.
 */

/**
 * The DuitNow proxy types. Comments carry PayNet's own code for each.
 *
 * A tuple rather than a union so zod schemas can take it directly and stay
 * typed; the union below is derived from it, which is what keeps the schema,
 * the Prisma enum and this module from drifting apart.
 */
export const DUITNOW_ID_TYPE_VALUES = [
  "MOBILE", // MBNO - numeric, country code, leading "+"
  "NRIC", // NRIC - numeric for the current 12-digit IC
  "BUSINESS_REG", // BREG - alphanumeric, hyphens excluded
  "PASSPORT", // PSPT - alphanumeric; issuing country is a separate field
  "ARMY_POLICE", // ARMN - alphanumeric, hyphens excluded
] as const;

export type DuitNowIdType = (typeof DUITNOW_ID_TYPE_VALUES)[number];

export type DuitNowIdTypeSpec = {
  value: DuitNowIdType;
  /** PayNet proxy code. Any future NAD/RPP integration addresses by this. */
  paynetCode: "MBNO" | "NRIC" | "BREG" | "PSPT" | "ARMN";
  /** Worded as the bank's own transfer screen words it, so the two match. */
  label: string;
  /** One line of what this actually is. */
  hint: string;
  placeholder: string;
};

/**
 * Order mirrors the bank transfer screen an admin actually uses, so the radio
 * a developer picks and the radio the admin picks read identically.
 */
export const DUITNOW_ID_TYPES: readonly DuitNowIdTypeSpec[] = [
  {
    value: "MOBILE",
    paynetCode: "MBNO",
    label: "Mobile No.",
    hint: "Your Malaysian mobile number, registered as a DuitNow ID.",
    placeholder: "012-345 6789",
  },
  {
    value: "NRIC",
    paynetCode: "NRIC",
    label: "NRIC/FIN",
    hint: "The 12 digits on your MyKad.",
    placeholder: "990101-14-1234",
  },
  {
    value: "BUSINESS_REG",
    paynetCode: "BREG",
    label: "Business Registration No.",
    hint: "Your SSM registration number, if you are paid as a business.",
    placeholder: "202001012345",
  },
  {
    value: "PASSPORT",
    paynetCode: "PSPT",
    label: "Passport No.",
    hint: "For non-Malaysians registered by passport.",
    placeholder: "A12345678",
  },
  {
    value: "ARMY_POLICE",
    paynetCode: "ARMN",
    label: "Army / Police No.",
    hint: "For serving personnel registered by service number.",
    placeholder: "T1234567",
  },
] as const;

export function isDuitNowIdType(value: unknown): value is DuitNowIdType {
  return (
    typeof value === "string" &&
    DUITNOW_ID_TYPE_VALUES.includes(value as DuitNowIdType)
  );
}

export function duitNowIdTypeSpec(type: DuitNowIdType): DuitNowIdTypeSpec {
  const spec = DUITNOW_ID_TYPES.find((entry) => entry.value === type);
  if (!spec) throw new Error(`Unknown DuitNow ID type: ${type}`);
  return spec;
}

export function duitNowIdTypeLabel(type: DuitNowIdType | null | undefined) {
  return type ? duitNowIdTypeSpec(type).label : "";
}

/**
 * Malaysian MOBILE numbers only, in +60 form.
 *
 * Deliberately separate from `MY_PHONE_REGEX` in payment-validation.ts, which
 * is shared with welcome-pack shipping where a landline is a perfectly good
 * courier contact number. Narrowing that one in place would reject valid
 * delivery phone numbers.
 *
 * `+60` then a mandatory `1` then 8-9 digits. Per MCMC's "Mobile Numbers
 * (3+8)" allocation only `011` carries 8 subscriber digits; every other
 * mobile prefix carries 7. Requiring the leading `1` excludes every landline
 * area code, whose national significant number starts 3-9. `015` is accepted
 * even though it is currently reserved/TSoIP — a false negative here would
 * block someone from being paid, which costs more than accepting an unusual
 * number that the bank will simply fail to resolve.
 */
export const MY_MOBILE_REGEX = /^\+601\d{8,9}$/;

/** A Malaysian landline in +60 form — national significant number starts 3-9. */
const MY_LANDLINE_REGEX = /^\+60[2-9]\d+$/;

const NRIC_REGEX = /^\d{12}$/;

/** PayNet permits alphanumerics for BREG/PSPT/ARMN and nothing else. */
const ALNUM_REGEX = /^[A-Z0-9]+$/;

const ALNUM_MIN = 4;
const ALNUM_MAX = 20;

/** Re-confirm payment details roughly twice a year. Advisory, never blocking. */
export const DUITNOW_CONFIRMATION_STALE_MS = 183 * 24 * 60 * 60 * 1000;

/**
 * Normalize a Malaysian phone number to +60 format. Handles 01X, 601X and
 * +601X inputs.
 *
 * Lives here rather than in payment-validation.ts so there is exactly one
 * implementation; payment-validation.ts re-exports it for its existing
 * callers, including welcome-pack shipping.
 */
export function normalizeMalaysianPhone(value: string): string {
  const cleaned = value.replace(/[-\s]/g, "");
  if (/^\+60\d{9,10}$/.test(cleaned)) return cleaned;
  if (/^60\d{9,10}$/.test(cleaned)) return `+${cleaned}`;
  if (/^0\d{9,10}$/.test(cleaned)) return `+6${cleaned}`;
  return cleaned;
}

/**
 * Month 1-12 and day 1-31, with no per-month or leap-year check.
 *
 * The leniency is the point — see the "deliberately NOT implemented" note at
 * the top of this file. Do not tighten this into a real calendar check.
 */
export function isValidNricDate(yymmdd: string): boolean {
  const mm = Number.parseInt(yymmdd.slice(2, 4), 10);
  const dd = Number.parseInt(yymmdd.slice(4, 6), 10);
  return mm >= 1 && mm <= 12 && dd >= 1 && dd <= 31;
}

/**
 * Canonical stored form for a proxy of this type.
 *
 * Dispatching on the type matters: the payment settings actions used to run
 * the phone normalizer over every proxy, which stripped the hyphen out of a
 * business registration number like `1234567-A` and rewrote a 10-digit
 * army/police number beginning `0` into a phone number.
 */
export function normalizeDuitNowId(type: DuitNowIdType, raw: string): string {
  const trimmed = raw.trim();
  if (!trimmed) return "";
  if (type === "MOBILE") return normalizeMalaysianPhone(trimmed);
  return trimmed.replace(/[-\s]/g, "").toUpperCase();
}

export type DuitNowIdRejectionReason =
  | "empty"
  | "mobile-is-landline"
  | "mobile-invalid"
  | "nric-wrong-length"
  | "nric-bad-date"
  | "charset"
  | "too-short"
  | "too-long";

export type DuitNowIdRejection = {
  reason: DuitNowIdRejectionReason;
  message: string;
};

/**
 * Returns null when the value is a plausible proxy of that type, or the reason
 * it isn't. Callers surface `message` verbatim, so a rejection always names
 * what is wrong rather than saying "invalid".
 *
 * "Plausible" is as far as any offline check can go — a well-formed ID that
 * was never registered is indistinguishable from one that was.
 */
export function checkDuitNowId(
  type: DuitNowIdType,
  raw: string,
): DuitNowIdRejection | null {
  const value = normalizeDuitNowId(type, raw);

  if (!value) {
    return {
      reason: "empty",
      message: `Enter your ${duitNowIdTypeSpec(type).label.replace(/\.$/, "")}.`,
    };
  }

  if (type === "MOBILE") {
    if (MY_MOBILE_REGEX.test(value)) return null;
    if (MY_LANDLINE_REGEX.test(value)) {
      return {
        reason: "mobile-is-landline",
        message:
          "That looks like a landline. A DuitNow mobile ID has to be a mobile number — registration is confirmed by SMS.",
      };
    }
    return {
      reason: "mobile-invalid",
      message:
        "Enter a Malaysian mobile number, e.g. 012-345 6789 or +60123456789.",
    };
  }

  if (type === "NRIC") {
    if (!NRIC_REGEX.test(value)) {
      return {
        reason: "nric-wrong-length",
        message: `A Malaysian NRIC is the 12 digits on your MyKad. You entered ${value.length} character${value.length === 1 ? "" : "s"}.`,
      };
    }
    if (!isValidNricDate(value)) {
      // 12 digits whose first six are not a date is far more often an e-wallet
      // or bank account number than a mistyped IC — but we cannot prove which,
      // so this is phrased as a hypothesis with the fix attached. Choosing
      // "Bank account" and picking TnG E-Wallet is a path that actually works.
      return {
        reason: "nric-bad-date",
        message:
          "The first 6 digits of an NRIC are your date of birth. If you copied this from your Touch 'n Go app, that is your eWallet account number, not your NRIC — choose Bank account instead and pick TnG E-Wallet.",
      };
    }
    return null;
  }

  if (!ALNUM_REGEX.test(value)) {
    return {
      reason: "charset",
      message: "Use letters and numbers only — no spaces or symbols.",
    };
  }
  if (value.length < ALNUM_MIN) {
    return {
      reason: "too-short",
      message: `That looks too short — a ${duitNowIdTypeSpec(type).label.replace(/\.$/, "").toLowerCase()} is at least ${ALNUM_MIN} characters.`,
    };
  }
  if (value.length > ALNUM_MAX) {
    return {
      reason: "too-long",
      message: `That looks too long — a ${duitNowIdTypeSpec(type).label.replace(/\.$/, "").toLowerCase()} is at most ${ALNUM_MAX} characters.`,
    };
  }
  return null;
}

/** Human-readable grouping. Display only — never store or send this form. */
export function formatDuitNowIdForDisplay(
  type: DuitNowIdType,
  value: string,
): string {
  const normalized = normalizeDuitNowId(type, value);
  if (!normalized) return "";

  if (type === "MOBILE" && MY_MOBILE_REGEX.test(normalized)) {
    const digits = normalized.slice(3); // drop "+60"
    const prefix = digits.slice(0, 2);
    const rest = digits.slice(2);
    const split = rest.length === 8 ? 4 : 3;
    return `+60${prefix}-${rest.slice(0, split)} ${rest.slice(split)}`;
  }

  if (type === "NRIC" && NRIC_REGEX.test(normalized)) {
    return `${normalized.slice(0, 6)}-${normalized.slice(6, 8)}-${normalized.slice(8)}`;
  }

  return normalized;
}

/**
 * Exactly what an admin should paste into the bank. This is the stored form,
 * not the pretty one — PayNet specifies MBNO as numeric with a leading "+" and
 * country code, and bank fields reject the separators humans read by.
 */
export function formatDuitNowIdForBank(
  type: DuitNowIdType,
  value: string,
): string {
  return normalizeDuitNowId(type, value);
}

/** Advisory only: payment details nobody has re-confirmed in about six months. */
export function isDuitNowConfirmationStale(
  checkedAt: Date | null | undefined,
  now: Date = new Date(),
): boolean {
  if (!checkedAt) return false;
  return now.getTime() - checkedAt.getTime() > DUITNOW_CONFIRMATION_STALE_MS;
}
