allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true

overrides:
  kysely: 0.28.17

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@prisma/engines'
  - prisma
