/** Mock data for NEXT_PUBLIC_DEV_MODE. All data is purely illustrative. */

export const MOCK_USER_ID = "dev-user-001";

export const MOCK_USER = {
  id: MOCK_USER_ID,
  name: "Alex Developer",
  email: "alex@mysverse.dev",
  emailVerified: true,
  image: null,
  createdAt: new Date("2024-06-01"),
  updatedAt: new Date("2025-05-20"),
};

export const MOCK_SESSION = {
  user: MOCK_USER,
  session: {
    id: "dev-session-001",
    userId: MOCK_USER_ID,
    token: "dev-token",
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    ipAddress: "127.0.0.1",
    userAgent: "DevMode",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
};

export const MOCK_USER_PROFILE = {
  id: MOCK_USER_ID,
  discordId: "123456789012345678",
  robloxId: "987654321",
  linearId: "dev-linear-001",
  linearEmail: "alex@mysverse.dev",
  legalName: "Alex Developer",
  shippingAddress: "123 Dev Street, KL 50000, Malaysia",
  role: "ADMIN" as const,
  developerRank: "DEVELOPER_COUNCIL" as const,
  specialties: ["SCRIPTING" as const],
  probationStartedAt: new Date("2024-06-01"),
  initialReviewAt: new Date("2024-07-01"),
  finalReviewAt: new Date("2024-09-01"),
  paymentMethod: "DUITNOW" as const,
  paypalEmail: null,
  duitNowId: "0123456789",
  bankName: "MAYBANK",
  bankAccountNumber: "512345678901",
  bankAccountName: "Alex Developer",
  robuxUsername: null,
  autoPayoutEnabled: true,
};

export const MOCK_TRANSACTIONS = [
  {
    id: "tx-001",
    userId: MOCK_USER_ID,
    linearIssueId: "linear-issue-101",
    linearIssueIdentifier: "MYS-101",
    linearIssueTitle: "Implement vehicle physics",
    linearIssueUrl: "https://linear.app/mysverse/issue/MYS-101",
    amount: 40,
    currency: "MYR",
    source: "PPT" as const,
    bonusPeriod: null,
    status: "PAID" as const,
    autoApproved: true,
    createdAt: new Date("2025-03-10"),
    paidAt: new Date("2025-03-12"),
    rejectedAt: null,
    rejectionReason: null,
    pdfBlobUrl: null,
  },
  {
    id: "tx-002",
    userId: MOCK_USER_ID,
    linearIssueId: "linear-issue-102",
    linearIssueIdentifier: "MYS-102",
    linearIssueTitle: "Refactor auth flow",
    linearIssueUrl: "https://linear.app/mysverse/issue/MYS-102",
    amount: 60,
    currency: "MYR",
    source: "PPT" as const,
    bonusPeriod: null,
    status: "PAID" as const,
    autoApproved: true,
    createdAt: new Date("2025-03-15"),
    paidAt: new Date("2025-03-17"),
    rejectedAt: null,
    rejectionReason: null,
    pdfBlobUrl: null,
  },
  {
    id: "tx-003",
    userId: MOCK_USER_ID,
    linearIssueId: "linear-issue-205",
    linearIssueIdentifier: "MYS-205",
    linearIssueTitle: "Build dashboard analytics",
    linearIssueUrl: "https://linear.app/mysverse/issue/MYS-205",
    amount: 80,
    currency: "MYR",
    source: "PPT" as const,
    bonusPeriod: null,
    status: "PENDING" as const,
    autoApproved: false,
    createdAt: new Date("2025-05-01"),
    paidAt: null,
    rejectedAt: null,
    rejectionReason: null,
    pdfBlobUrl: null,
  },
  {
    id: "tx-004",
    userId: MOCK_USER_ID,
    linearIssueId: null,
    linearIssueIdentifier: null,
    linearIssueTitle: "April 2025 Bonus",
    linearIssueUrl: null,
    amount: 120,
    currency: "MYR",
    source: "BONUS" as const,
    bonusPeriod: "2025-04",
    status: "PAID" as const,
    autoApproved: false,
    createdAt: new Date("2025-05-05"),
    paidAt: new Date("2025-05-07"),
    rejectedAt: null,
    rejectionReason: null,
    pdfBlobUrl: null,
  },
  {
    id: "tx-005",
    userId: MOCK_USER_ID,
    linearIssueId: "linear-issue-310",
    linearIssueIdentifier: "MYS-310",
    linearIssueTitle: "Add notification system",
    linearIssueUrl: "https://linear.app/mysverse/issue/MYS-310",
    amount: 40,
    currency: "MYR",
    source: "PPT" as const,
    bonusPeriod: null,
    status: "PENDING" as const,
    autoApproved: false,
    createdAt: new Date("2025-05-18"),
    paidAt: null,
    rejectedAt: null,
    rejectionReason: null,
    pdfBlobUrl: null,
  },
  {
    id: "tx-006",
    userId: MOCK_USER_ID,
    linearIssueId: "linear-issue-150",
    linearIssueIdentifier: "MYS-150",
    linearIssueTitle: "Fix CSS alignment",
    linearIssueUrl: "https://linear.app/mysverse/issue/MYS-150",
    amount: 20,
    currency: "MYR",
    source: "PPT" as const,
    bonusPeriod: null,
    status: "REJECTED" as const,
    autoApproved: false,
    createdAt: new Date("2025-04-20"),
    paidAt: null,
    rejectedAt: new Date("2025-04-22"),
    rejectionReason: "Duplicate of MYS-149",
    pdfBlobUrl: null,
  },
];

export const MOCK_BONUS_CANDIDATES = [
  {
    id: "bc-001",
    linearIssueId: "linear-bonus-401",
    linearIssueIdentifier: "MYS-401",
    linearIssueTitle: "Add search filters",
    linearIssueUrl: "https://linear.app/mysverse/issue/MYS-401",
    linearIssueStateType: "started",
    linearIssueStateName: "In Progress",
    labels: ["Enhancement"],
    estimate: 2,
    userId: MOCK_USER_ID,
    assigneeLinearId: "dev-linear-001",
    assigneeEmail: "alex@mysverse.dev",
    assigneeName: "Alex Developer",
    currency: "MYR",
    maxAmount: 40,
    approvedAmount: null,
    status: "ELIGIBLE" as const,
    ineligibilityReason: null,
    period: "2025-05",
    completedAt: null,
    reviewedById: null,
    reviewedBy: null,
    reviewedAt: null,
    rejectionReason: null,
    transactionId: null,
    transaction: null,
    notifications: [],
    createdAt: new Date("2025-05-10"),
    updatedAt: new Date("2025-05-10"),
  },
  {
    id: "bc-002",
    linearIssueId: "linear-bonus-402",
    linearIssueIdentifier: "MYS-402",
    linearIssueTitle: "Improve error handling",
    linearIssueUrl: "https://linear.app/mysverse/issue/MYS-402",
    linearIssueStateType: "completed",
    linearIssueStateName: "Done",
    labels: ["Bug Fix"],
    estimate: 3,
    userId: MOCK_USER_ID,
    assigneeLinearId: "dev-linear-001",
    assigneeEmail: "alex@mysverse.dev",
    assigneeName: "Alex Developer",
    currency: "MYR",
    maxAmount: 60,
    approvedAmount: null,
    status: "READY_FOR_REVIEW" as const,
    ineligibilityReason: null,
    period: "2025-05",
    completedAt: new Date("2025-05-15"),
    reviewedById: null,
    reviewedBy: null,
    reviewedAt: null,
    rejectionReason: null,
    transactionId: null,
    transaction: null,
    notifications: [],
    createdAt: new Date("2025-05-08"),
    updatedAt: new Date("2025-05-15"),
  },
  {
    id: "bc-003",
    linearIssueId: "linear-bonus-403",
    linearIssueIdentifier: "MYS-403",
    linearIssueTitle: "Write unit tests",
    linearIssueUrl: "https://linear.app/mysverse/issue/MYS-403",
    linearIssueStateType: "completed",
    linearIssueStateName: "Done",
    labels: ["Testing"],
    estimate: 2,
    userId: MOCK_USER_ID,
    assigneeLinearId: "dev-linear-001",
    assigneeEmail: "alex@mysverse.dev",
    assigneeName: "Alex Developer",
    currency: "MYR",
    maxAmount: 40,
    approvedAmount: 30,
    status: "APPROVED" as const,
    ineligibilityReason: null,
    period: "2025-04",
    completedAt: new Date("2025-04-20"),
    reviewedById: "dev-user-002",
    reviewedBy: null,
    reviewedAt: new Date("2025-04-25"),
    rejectionReason: null,
    transactionId: "tx-004",
    transaction: null,
    notifications: [],
    createdAt: new Date("2025-04-05"),
    updatedAt: new Date("2025-04-25"),
  },
  {
    id: "bc-004",
    linearIssueId: "linear-bonus-404",
    linearIssueIdentifier: "MYS-404",
    linearIssueTitle: "Update readme",
    linearIssueUrl: "https://linear.app/mysverse/issue/MYS-404",
    linearIssueStateType: "completed",
    linearIssueStateName: "Done",
    labels: ["Documentation"],
    estimate: 1,
    userId: MOCK_USER_ID,
    assigneeLinearId: "dev-linear-001",
    assigneeEmail: "alex@mysverse.dev",
    assigneeName: "Alex Developer",
    currency: "MYR",
    maxAmount: 20,
    approvedAmount: null,
    status: "REJECTED" as const,
    ineligibilityReason: null,
    period: "2025-04",
    completedAt: new Date("2025-04-18"),
    reviewedById: "dev-user-002",
    reviewedBy: null,
    reviewedAt: new Date("2025-04-25"),
    rejectionReason: "Out of scope",
    transactionId: null,
    transaction: null,
    notifications: [],
    createdAt: new Date("2025-04-10"),
    updatedAt: new Date("2025-04-25"),
  },
];

export const MOCK_LINKED_ACCOUNTS = [
  { providerId: "linear", accountId: "dev-linear-001" },
  { providerId: "discord", accountId: "123456789012345678" },
  { providerId: "roblox", accountId: "987654321" },
];

export const MOCK_KYC_VERIFICATION = {
  id: "kyc-001",
  userId: MOCK_USER_ID,
  status: "APPROVED" as const,
  legalName: "Alex Developer",
  documentType: "mykad",
  rejectionReason: null,
  submittedAt: new Date("2024-08-01"),
  reviewedAt: new Date("2024-08-03"),
};

export const MOCK_SIGNED_DOCUMENTS = [
  {
    id: "doc-001",
    userId: MOCK_USER_ID,
    documentType: "NDA" as const,
    templateVersion: "2024-06",
    templateContent: "...",
    legalName: "Alex Developer",
    signedAt: new Date("2024-06-15"),
    ipAddress: "127.0.0.1",
    coiEntries: [],
  },
  {
    id: "doc-002",
    userId: MOCK_USER_ID,
    documentType: "COI" as const,
    templateVersion: "2024-06",
    templateContent: "...",
    legalName: "Alex Developer",
    signedAt: new Date("2024-06-15"),
    ipAddress: "127.0.0.1",
    coiEntries: [],
  },
];

export const MOCK_PPT_REQUESTS: unknown[] = [];

export const MOCK_LEADERBOARD_PROFILES = [
  {
    id: "dev-user-002",
    legalName: "Bella Chen",
    linearId: "dev-linear-002",
    linearEmail: "bella@mysverse.dev",
    role: "DEVELOPER" as const,
    developerRank: "DEVELOPER" as const,
    paymentMethod: "PAYPAL" as const,
    user: { name: "Bella Chen", email: "bella@mysverse.dev" },
  },
  {
    id: "dev-user-003",
    legalName: "Carlos Rivera",
    linearId: "dev-linear-003",
    linearEmail: "carlos@mysverse.dev",
    role: "DEVELOPER" as const,
    developerRank: "DEVELOPER" as const,
    paymentMethod: "PAYPAL" as const,
    user: { name: "Carlos Rivera", email: "carlos@mysverse.dev" },
  },
  {
    id: "dev-user-004",
    legalName: "Diana Kim",
    linearId: "dev-linear-004",
    linearEmail: "diana@mysverse.dev",
    role: "DEVELOPER" as const,
    developerRank: "DEVELOPER" as const,
    paymentMethod: "PAYPAL" as const,
    user: { name: "Diana Kim", email: "diana@mysverse.dev" },
  },
  {
    id: "dev-user-005",
    legalName: "Ethan Lim",
    linearId: "dev-linear-005",
    linearEmail: "ethan@mysverse.dev",
    role: "DEVELOPER" as const,
    developerRank: "DEVELOPER" as const,
    paymentMethod: "PAYPAL" as const,
    user: { name: "Ethan Lim", email: "ethan@mysverse.dev" },
  },
  {
    id: "dev-user-006",
    legalName: "Farah Ahmad",
    linearId: "dev-linear-006",
    linearEmail: "farah@mysverse.dev",
    role: "DEVELOPER" as const,
    developerRank: "DEVELOPER" as const,
    paymentMethod: "PAYPAL" as const,
    user: { name: "Farah Ahmad", email: "farah@mysverse.dev" },
  },
];

export const MOCK_WELCOME_PACK_ORDER = null;
